# Exercise 2 - Learn Concat

Let's continue from Exercise 1. First learn what does pandas.concat function do?

A) Here are thwo simple dataframes:

```python
df1 = pd.DataFrame({
    "country": ["Belize", "Liechtenstein", "Bhutan"],
    "population": [417_000, 40_000, 790_000]
})

df2 = pd.DataFrame({
    "country": ["Suriname", "São Tomé and Príncipe", "Tuvalu"],
    "population": [630_000, 240_000, 10_000]
})
```

use pandas.concat to put them in one data frame called df.

``` python
df = pd.concat([df1, df2])
df.head(6)
```

B) Use sort_values()-method to sort DataFrame df by population in ascending order.

```python
# With ignore_index=True: pandas discards the old labels and assigns a fresh 0, 1, 2, 3, 4, 5.
df = df.sort_values(by="population", ignore_index=True)
df.head()
```

C) What is the difference between pandas.concat([df1,df2], axis = 0) and pandas.concat([df1,df2], axis = 1)

```
axis=0 (default) — stack rows (vertical): Rows of df2 are appended below rows of df1. Columns must match (or be unioned with NaN fills). Result has more rows, same columns. The result will be a DataFrame with 2 columns (excluding the index) and 6 rows.

axis=1 — stack columns (horizontal): Columns of df2 are placed beside columns of df1. Result has more columns, same rows (aligned by index). The result will be a DataFrame with 4 columns (excluding the index) and 3 rows.
```

D) What does df.loc[0] now return? 

```
df.loc[0] returns the row at label 0:
    country       Tuvalu
    population     10000
    Name: 0, dtype: object
```

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "country": ["Belize", "Liechtenstein", "Bhutan"],
    "population": [417_000, 40_000, 790_000]
})

df2 = pd.DataFrame({
    "country": ["Suriname", "São Tomé and Príncipe", "Tuvalu"],
    "population": [630_000, 240_000, 10_000]
})

df = pd.concat([df1, df2], axis=0)
df.head(6)

                 country  population
0                 Belize      417000
1          Liechtenstein       40000
2                 Bhutan      790000
0               Suriname      630000
1  São Tomé and Príncipe      240000
2                 Tuvalu       10000

In [2]:
# With ignore_index=True: pandas discards the old labels and assigns a fresh 0, 1, 2, 3, 4, 5.
df.sort_values(by="population", ignore_index=True, inplace=True)
df.head()

                 country  population
0                 Tuvalu       10000
1          Liechtenstein       40000
2  São Tomé and Príncipe      240000
3                 Belize      417000
4               Suriname      630000

In [3]:
df.loc[0]

country       Tuvalu
population     10000
Name: 0, dtype: object