# Exploring The Star Wars Dataset with The Pandas Library

In [36]:
import pandas as pd

If you don't have the pandas library installed you can install it with uncommenting the following:

In [37]:
#!pip install pandas

If you have the data set in your computer, you can use the path. Remember to replace backslash to slash: \ -> /
For example: "C:\Users\user1\star_wars\star_wars\csv\characters.csv" becomes "C:/Users/user1/star_wars/star_wars/csv/characters.csv"
You can also download the library from the Internet

**Use pandas read_csv function to read in the data**

In [38]:
df_characters = pd.read_csv("https://raw.githubusercontent.com/planetacomputer/starwars-full/main/characters.csv")

**Examine the top 2 rows**

In [39]:
df_characters.head(2)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
1,2,Leia Organa,Human,Female,1.50,49.0,Brown,Brown,Light,19.0,Alderaan,35.0,A leader in the Rebel Alliance and twin sister...

**Print the column names**

In [40]:
df_characters.columns

Index(['id', 'name', 'species', 'gender', 'height', 'weight', 'hair_color',
       'eye_color', 'skin_color', 'year_born', 'homeworld', 'year_died',
       'description'],
      dtype='object')

**Print the datatypes**

In [41]:
df_characters.dtypes

id               int64
name            object
species         object
gender          object
height         float64
weight         float64
hair_color      object
eye_color       object
skin_color      object
year_born      float64
homeworld       object
year_died      float64
description     object
dtype: object

## Exercises

### Selecting columns

Select only one column

In [42]:
df_characters[["name"]].head(3)

             name
0  Luke Skywalker
1     Leia Organa
2     Darth Vader

Select multiple columns:

In [43]:
df_characters[["name","species","gender","height"]].head(3)

             name species  gender  height
0  Luke Skywalker   Human    Male    1.72
1     Leia Organa   Human  Female    1.50
2     Darth Vader   Human    Male    2.02

Extra exercise: first put the columns name in a list and then use the variable name instead

### Filtering

Select only lines where height is over 1.5 m

In [44]:
df_characters[df_characters["height"] > 1.5].head(3)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.

Under the hood pandas produces a boolean array and that is used to make selection

In [45]:
df_characters["height"] > 1.5

0      True
1     False
2      True
3     False
4      True
      ...
91     True
92     True
93     True
94     True
95    False
Name: height, Length: 96, dtype: bool

Filtering with multiple conditions when both conditions must be true, we use **&**. Syntax is the following: **df_characters[ (condition 1) & (condintion 2)]** Note that we use & instead of **and**.

In [46]:
df_characters[ ( df_characters["species"] == "Human") & ( df_characters["height"] > 2.0 ) ]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.

**Pandas logical operators are:**

& = bitwise AND operator

| = bitwise OR operator

~ = bitwise NOT operator

We can combine the operators. Here we choose characters whose eye_color is **not** Blue nor Brown or whose hair color is white

In [47]:
df_characters[ (  ~ df_characters["eye_color"].isin(["Blue","Brown"]) ) | ( df_characters["hair_color"] == "White" ) ].head(5)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896.0,Unknown,4.0,A wise and powerful Jedi Master.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.
6,7,Obi-Wan Kenobi,Human,Male,1.82,81.0,White,Blue-gray,Light,57.0,Stewjon,0.0,A Jedi Master who mentored Anakin and Luke Sky...
7,8,Emperor Palpatine,Human,Male,1.73,75.0,NaN,Yellow,Pale,82.0,Naboo,35.0,The Sith Lord who became Emperor of the galaxy.

In [48]:
df_characters["skin_color"].value_counts()

skin_color
Light         50
Green         10
Dark           9
Pale           7
Blue           6
Brown          4
Orange         4
Red            2
Gold           1
White          1
White/Blue     1
Gray           1
Name: count, dtype: int64

## EXERCISES

!!!!! **Exercise 1 - 6 you have to be able to present **without** computer, so learn them by ❤️** !!!!!

### Exercise 1 - ✏️🧠

Select from df_characters only columns **name, species, hair_color, eye_color**

In [49]:
## Write your answer here
compact_df = df_characters[["name", "species", "hair_color", "eye_color"]]
compact_df.head(10)

                name         species hair_color  eye_color
0     Luke Skywalker           Human      Blond       Blue
1        Leia Organa           Human      Brown      Brown
2        Darth Vader           Human        NaN     Yellow
3               Yoda  Yoda's species      White      Brown
4           Han Solo           Human      Brown      Hazel
5          Chewbacca         Wookiee      Brown       Blue
6     Obi-Wan Kenobi           Human      White  Blue-gray
7  Emperor Palpatine           Human        NaN     Yellow
8   Anakin Skywalker           Human      Blond       Blue
9      Padmé Amidala           Human      Brown      Brown

### Exercise 2 - ✏️🧠

Select from df_characters that are less than 1.0 meter

In [50]:
## Write your answer here
less_than_10_meter_df = df_characters[df_characters["height"] < 1.0]
less_than_10_meter_df.head(10)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896.0,Unknown,4.0,A wise and powerful Jedi Master.
20,21,R2-D2,Droid,NaN,0.96,NaN,NaN,NaN,White/Blue,33.0,Naboo,NaN,An astromech droid known for his bravery and r...

### Exercise 3 - ✏️🧠

Select from df_characters whose skin color is **Green** and select only columns **name, species, gender**

In [51]:
## Write your answer here
execise_3_df = df_characters[
    df_characters["skin_color"] == "Green"
    ]
[["name", "species", "gender"]]
execise_3_df.head()

'''We can do in alternative way'''
exercise_3_df = df_characters.loc[
    df_characters["skin_color"] == "Green", 
    ["name", "species", "gender"]
]
exercise_3_df.head()

             name         species  gender
3            Yoda  Yoda's species    Male
32  Barriss Offee        Mirialan  Female
35          Bossk      Trandoshan    Male
39         Greedo          Rodian    Male
40  Hera Syndulla         Twi'lek  Female

### Exercise 4 - ✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **Red**.

In [ ]:
## Write your answer here
exercise_4_df = df_characters.loc[
    (df_characters["eye_color"] == "Blue") &
    (df_characters["hair_color"] == "Red")
]
exercise_4_df.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
24,25,General Hux,Human,Male,1.85,75.0,Red,Blue,Light,0.0,Arkanis,35.0,A general in the First Order.
45,46,Mon Mothma,Human,Female,1.70,55.0,Red,Blue,Light,48.0,Chandrila,NaN,A leader in the Rebel Alliance.

### Exercise 5 -✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **NOT** **Red**.

In [53]:
## Write your answer here
exercise_5_df = df_characters.loc[
    (df_characters["eye_color"] == "Blue") &
    ~((df_characters["hair_color"] == "Red"))
]
exercise_5_df.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
8,9,Anakin Skywalker,Human,Male,1.88,84.0,Blond,Blue,Light,41.0,Tatooine,4.0,A Jedi Knight who fell to the dark side and be...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.

### Exercise 6 - ✏️🧠

Find all characters who are taller than 180 cm AND weigh more than 80 kg.

In [54]:
## Write your answer here
# NOTE: 180 cm = 1.8 m
exercise_6_df = df_characters.loc[
    (df_characters["height"] > 1.8) &
    (df_characters["weight"] > 80)
]
exercise_6_df.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
6,7,Obi-Wan Kenobi,Human,Male,1.82,81.0,White,Blue-gray,Light,57.0,Stewjon,0.0,A Jedi Master who mentored Anakin and Luke Sky...
8,9,Anakin Skywalker,Human,Male,1.88,84.0,Blond,Blue,Light,41.0,Tatooine,4.0,A Jedi Knight who fell to the dark side and be...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.

### Exercise 7 - 💻 ✅

Hint: You can use isin() function to filter through a list: df_characters[df_characters["eye_color"].isin(["Blue","Brown"])]

Select characters whose **eye_color** is not either **Blue** or **Brown**, and whose **hair_color** is **Green**.

In [55]:
## Write you answer to here
# NOTE: This execise does not contains data!
exercise_7_df = df_characters.loc[
    (~df_characters["eye_color"].isin(["Blue", "Brown"])) & 
    (df_characters["hair_color"] == "Green")
]
exercise_7_df.head()

Empty DataFrame
Columns: [id, name, species, gender, height, weight, hair_color, eye_color, skin_color, year_born, homeworld, year_died, description]
Index: []

### Exercise 8 - 💻 ✅

Find characters who are taller than 180 cm, are not human, and do not weigh more than 100 kg.

In [56]:
## Write your answer to here
exercise_8_df = df_characters.loc[
    (df_characters["height"] > 1.8) & 
    (~(df_characters["species"] == "Human")) &
    (df_characters["weight"] < 100)
]
exercise_8_df.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52.0,Naboo,NaN,A clumsy Gungan who became a representative in...
34,35,Bib Fortuna,Twi'lek,Male,1.93,65.0,NaN,Red,Pale,60.0,Ryloth,35.0,A majordomo for Jabba the Hutt.
43,44,Kit Fisto,Nautolan,Male,1.96,87.0,NaN,Black,Green,48.0,Glee Anselm,19.0,A Jedi Master known for his underwater combat ...
47,48,Plo Koon,Kel Dor,Male,1.88,80.0,NaN,Black,Orange,44.0,Dorin,19.0,A Jedi Master known for his unique mask.
50,51,Shaak Ti,Togruta,Female,1.87,68.0,NaN,Black,Red,43.0,Shili,NaN,A Jedi Master and member of the Jedi High Coun...

### Exercise 9 - 💻 ✅

Find characters who are either female and taller than 160 cm, OR male and taller than 190 cm.

In [57]:
## Write your answer to here
exercise_9_df = df_characters.loc[
    ((df_characters["gender"] == "Female") & 
    (df_characters["height"] > 1.6)) |
    ((df_characters["gender"] == "Male") &
    (df_characters["height"] > 1.9))
]
exercise_9_df.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
9,10,Padmé Amidala,Human,Female,1.65,45.0,Brown,Brown,Light,46.0,Naboo,19.0,The queen-turned-senator of Naboo and wife of ...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52.0,Naboo,NaN,A clumsy Gungan who became a representative in...

### Exercise 10 - 💻 ✅

**Let's take a subset of the data**

In [58]:
df_droids = df_characters[df_characters["species"] == "Droid"][["name","homeworld","description"]]

There are 4 droids

In [59]:
df_droids

     name homeworld                                        description
18   BB-8       NaN                       A spherical astromech droid.
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 1**: What is happening in the code below? Which lines are selected and why?

In [60]:
df_droids[[False,True,True,True]]
# WHAT IS HAPPENING:
# Direct bracket indexing with a list of booleans filters the DataFrame rows by positional order.
#
# WHICH LINES ARE SELECTED:
# Rows at positional index 1, 2, and 3 (the 2nd, 3rd, and 4th rows of the DataFrame).
#
# WHY:
# Pandas maps each boolean value 1-to-1 to the DataFrame's rows in sequential order:
# - Position 0 (1st row) -> False (Excluded)
# - Position 1 (2nd row) -> True  (Included)
# - Position 2 (3rd row) -> True  (Included)
# - Position 3 (4th row) -> True  (Included)
#
# NOTE: The boolean list length must EXACTLY match the total number of rows in df_droids,
# otherwise Pandas will raise a ValueError.

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 2**: Why does this code produce the similar output?

In [61]:
df_droids[df_droids["name"].str.len() == 5]

# WHAT IS HAPPENING:
# Filters df_droids to return rows where the string length of the 'name' column is exactly 5 characters.
#
# WHY IT PRODUCES A SIMILAR OUTPUT:
# The similar result is purely coincidental (a "lucky case") based on the current dataset:
# the last 3 rows happen to have 5-letter names (e.g., 'C-3PO', 'R2-D2', or 'L3-37' depending on data), 
# while the 1st row does not ('BB-8' has only 4 characters).
#
# CRITICAL DIFFERENCE:
# - Previous code: Hardcoded row positions (positional selection via a boolean list).
# - This code: Dynamic conditional filtering based on data values.
# If the 'name' values change (becoming shorter or longer than 5 characters), 
# the returned rows will change accordingly.

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

### Bonus exercise 🐇🕳️

First make sure **numpy** is installed

In [62]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)

In [63]:
import numpy as np

There is a problem in this code. Google/Use LLM to find out why it doesn't work.

In [64]:
# df_droids[([True,False,True,False]) & ([False,True,False,False])]

# First of all, there is a syntax error.
# If we run it, we can see: TypeError: unsupported operand type(s) for &: 'list' and 'list'
# That means the operator & cannot be applied to two list datatypes.
# To fix it, convert them into arrays (or Series), not lists.

df_droids[np.array([True,False,True,False]) & np.array([False,True,False,False])]


# This is dead code! Check the bitwise computed conditions one by one; we always get False for all.
# So, this code always returns an empty result!
# True & False = False
# False & True = False
# True & False = False
# False & False = False

# So, this code serves no purpose (returns empty list)!

Empty DataFrame
Columns: [name, homeworld, description]
Index: []

However this works

In [65]:
np.array([True, False, True, False]) & np.array([False, True, False, False])

# I've explained in the previous code block!
# To fix it, convert them into arrays (or Series), not lists.

array([False, False, False, False])

**Question 1**: Use that syntax to make the original failing df_droid selection work?

**Question 2**: What does this tell about inner working of pandas? Does it work with numpy or basic python under the hood?